Repository tridactyl/tridactyl, pull requests merged in 2018-10, with the labels that each got.

#1077 Extend zoom excmd keybindings and improve documentation.
  src/excmds.ts
  src/lib/config.ts
Labels: awaiting author : )

#1072 [RFC] Try to make exclaim give better errors
  src/excmds.ts
  src/lib/config.ts
Labels: awaiting author : )

#1082 Allow `scrollto` to accept arguments specified in radians
  src/excmds.ts
Labels: P1

#1105 commandline_frame.ts: Try to get rid of input lag
  src/commandline_frame.ts
Labels: needs review

#1100 Add halloween theme
  src/content.ts
  src/static/themes/halloween/halloween.css
Labels: P1, needs review
