Repository tridactyl/tridactyl, pull requests merged in 2018-07, with the labels that each got.

#736 Add private window indicator to bufferall
  src/completions/BufferAll.ts
  src/static/css/commandline.css
  src/static/themes/default.css
Labels: needs review

#648 {excmds,controller}.ts: Fix race condition in state.mode synchronization
  src/controller.ts
  src/excmds.ts
  src/state.ts
Labels: needs review

#741 {excmds,webext,messaging}.ts: Remove l() promise logger
  src/excmds.ts
  src/lib/webext.ts
  src/messaging.ts
Labels: needs review

#583 Use fillcmdline to provide feeback from yank [Fixes #138]
  src/excmds.ts
Labels: blocked

#737 Implement url2args excmd
  src/excmds.ts
Labels: needs review

#767 Add condition for the -b open in background argument for completions
  src/completions/History.ts
Labels: awaiting author : )
