Repository tridactyl/tridactyl, pull requests merged in 2019-10, with the labels that each got.

#1877 Revert fixamo
  src/background.ts
  src/lib/native.ts
  src/static/newtab.md
  src/static/unfixamo.html
Labels: P1, needs review

#1879 Remove `set csp clobber`
  .tridactylrc
  contributing.md
  doc/troubleshooting.md
  src/background.ts
  src/excmds.ts
  src/lib/config.ts
Labels: P1, needs review

#1764 :source race conditions
  src/lib/config.ts
Labels: needs review

#1765 :set storageloc local
  src/lib/config.ts
Labels: needs review

#1816 Optimize addJump scroll handler and fix stale data usage.
  src/excmds.ts
Labels: awaiting author : )

#1891 Unfixamo2
  src/excmds.ts
  src/lib/config.ts
  src/lib/native.ts
  src/static/unfixamo.html
Labels: blocked
