Repository tridactyl/tridactyl, pull requests merged in 2019-02, with the labels that each got.

#1301 Option to disable javascript hinting
  src/content/hinting.ts
  src/excmds.ts
Labels: needs review

#1310 excmds.ts: use word "disable" in mode/blacklistadd doc
  src/excmds.ts
Labels: awaiting author : )

#1321 Add doc
  contributing.md
Labels: needs review

#1324 commandline_frame.ts: Simplify completion-updating mechanism
  src/commandline_frame.ts
Labels: needs review

#1335 Fix findnext
  src/content/finding.ts
  src/excmds.ts
  src/state.ts
Labels: needs review

#1355 nativeopen: detect profile, enable space in URLs
  src/background/native_background.ts
  src/excmds.ts
Labels: needs review

#1339 Cancel key{up,press} evts when corresponding keydown is cancelled
  src/content.ts
  src/content/controller_content.ts
Labels: needs review

#1372 feat/minor: add hint that scrolls element to the top of a page
  src/excmds.ts
  src/lib/config.ts
Labels: needs review

#1382 native.ts: implement proper profile-checking
  src/excmds.ts
  src/lib/native.ts
Labels: blocked, needs review

#1383 MacOS build fixes.
  scripts/bodgecss.sh
  scripts/pretty
Labels: needs review
