Repository tridactyl/tridactyl, pull requests merged in 2019-05, with the labels that each got.

#1534 Add arrows navigation in the hint mode
  src/content/hinting.ts
Labels: needs review

#1499 [RFC] This is a test
  .circleci/config.yml
  package-lock.json
  package.json
  scripts/common
  tests/excmds.test.ts
Labels: awaiting author : )

#1591 content.ts: Fix pages autofocusing elements
  src/content.ts
  src/lib/config.ts
Labels: needs review

#862 Default bookmark name when bookmark function is not provided a title
  src/excmds.ts
Labels: awaiting author : ), good first issue

#1608 finding.ts: fix `:find` and `:findnext` sucking hard
  src/content/finding.ts
  src/excmds.ts
Labels: needs review
