Repository tridactyl/tridactyl, pull requests merged in 2020-05, with the labels that each got.

#2355 Fix #2338: stop subconfig unbinds being forgotten
  src/lib/config.ts
Labels: needs review

#2299 excmds.ts: implement `tabslideshow`
  src/excmds.ts
  src/lib/webext.ts
Labels: needs review

#2300 hinting: implement quickhint shifting
  src/content/hinting.ts
  src/lib/config.ts
Labels: needs review

#2208 WIP: move state storage to background
  src/commandline_frame.ts
  src/content.ts
  src/content/finding.ts
  src/excmds.ts
  src/lib/commandline_cmds.ts
  src/lib/controller.ts
  src/lib/webext.ts
  src/state.ts
  webpack.config.js
Labels: P1

#2384 Scrolling.ts refactor
  src/content/scrolling.ts
Labels: needs review

#2416 Display hints on the right elements
  src/content/hinting.ts
Labels: needs review

#1838 Add recontain excmd
  src/excmds.ts
  src/lib/containers.ts
Labels: awaiting author : ), good first issue
