Repository tridactyl/tridactyl, pull requests merged in 2023-12, with the labels that each got.

#4809 Reduce likelihood of losing characters while command line is opening
  src/commandline_frame.ts
  src/content/commandline_content.ts
  src/content/controller_content.ts
  src/excmds.ts
  src/lib/messaging.ts
Labels: needs review, blocks-next-release

#4844 Add functions to move cursor up and down in text areas
  src/lib/editor.ts
Labels: needs review

#4791 Fix wrong behavior of :tabopen with containers
  src/excmds.ts
Labels: blocks-next-release
